id: I402C4967
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:02:15+00:00'
last_modified: '2022-06-09T05:02:11.900402+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16704
  title: མི་ཚེའི་དབྱངས་རྟ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    FC4B:
      image_group_id: I2PD18259
      title: ''
      total_pages: 298
      order: 1
      base_file: FC4B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
